=== BrianKolowitz/data-focused-python/lectures/Topic 05 - Processing files/scores.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="scores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="score" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:date" name="date"/>
              <xs:element type="xs:string" name="home-team"/>
              <xs:element type="xs:int" name="home-score"/>
              <xs:element type="xs:string" name="away-team"/>
              <xs:element type="xs:int" name="away-score"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BrianKolowitz/data-focused-python/lectures/_site/Week 02 - Processing files using functions, classes, and libraries/scores2.xml
<scores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scores.xsd">
    <score>
        <date>2019-05-01</date>
        <home-team>Pirates</home-team>
        <home-score>0</home-score>
        <away-team>Cubs</away-team>
        <away-score>10</away-score>
    </score>
    <score>
        <date>2019-05-05</date>
        <home-team>Reds</home-team>
        <home-score>7</home-score>
        <away-team>Pirates</away-team>
        <away-score>0</away-score>
    </score>
</scores>
